package info.dourok.voicebot

import androidx.test.platform.app.InstrumentationRegistry
import androidx.test.ext.junit.runners.AndroidJUnit4
import info.dourok.voicebot.data.voice.MicroFeaturesEngine
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.json.JSONObject

/**
 * Verifies the native MicroFeaturesEngine (app/src/main/cpp/micro_features_jni.cpp, wrapping the
 * vendored TFLite Micro audio frontend) produces the same 40-dim feature frames as the real
 * Python `pymicro_features` reference implementation for the same real "Mai ơi" recording.
 *
 * The fixtures under assets/mai_oi_parity/ were generated by
 * `robot-esp32/services/wakeword_training/.venv-train`'s pymicro_features against
 * `/Users/lucnguyen/Documents/mai_oi_speech/rec_nomal.wav` (16kHz mono PCM16, standard 44-byte
 * WAV header -- verified against the actual file, not assumed).
 *
 * pymicro_features' `process_samples()` only consumes as much of its input as fits whole
 * window/step increments per call (mirrored by the native side's internal loop in
 * micro_features_jni.cpp), so the reference generation script looped over the full recording,
 * feeding the unconsumed remainder back in until every sample was accounted for -- see
 * expected_features.json's "samples_read" field, which equals the full sample count of
 * reference.wav. The resulting `features` field is a list of per-frame lists (NOT a flat list --
 * verified against the real pymicro_features output before writing this test), one 40-float list
 * per 10ms frame, matching the shape `MicroFeaturesEngine.processSamples()` returns
 * (`Array<FloatArray>`).
 */
@RunWith(AndroidJUnit4::class)
class MicroFeaturesEngineParityTest {

    @Test
    fun nativeFeaturesMatchPythonReference() {
        // Fixture assets live under androidTest/assets, which get packaged into the *test* APK,
        // not the app-under-test APK -- so they must be read via the instrumentation context
        // (bound to the test package), not targetContext (bound to the app under test). Using
        // targetContext here throws FileNotFoundException even though the test compiles and the
        // files genuinely exist on device (verified on a real R1 run before this fix landed).
        val instrumentationContext = InstrumentationRegistry.getInstrumentation().context
        val wavBytes = instrumentationContext.assets.open("mai_oi_parity/reference.wav").readBytes()
        val pcm = extractPcm16Mono(wavBytes)

        val expectedJson = JSONObject(
            instrumentationContext.assets.open("mai_oi_parity/expected_features.json")
                .bufferedReader().readText()
        )
        val expectedFrames = expectedJson.getJSONArray("features")

        val engine = MicroFeaturesEngine()
        assertTrue("engine failed to initialize", engine.isReady)
        val produced = engine.processSamples(pcm)
        engine.destroy()

        assertEquals(
            "frame count mismatch -- expected_features.json has ${expectedFrames.length()} " +
                "frames, native engine produced ${produced.size}",
            expectedFrames.length(), produced.size,
        )

        for (frameIndex in 0 until expectedFrames.length()) {
            val expectedFrame = expectedFrames.getJSONArray(frameIndex)
            val actualFrame = produced[frameIndex]
            assertEquals(
                "frame[$frameIndex] dimension mismatch",
                expectedFrame.length(), actualFrame.size,
            )
            for (i in 0 until expectedFrame.length()) {
                val expected = expectedFrame.getDouble(i)
                val actual = actualFrame[i].toDouble()
                assertTrue(
                    "frame[$frameIndex][$i]: expected=$expected actual=$actual (tolerance 1e-3)",
                    Math.abs(expected - actual) < 1e-3,
                )
            }
        }
    }

    /**
     * Strips the WAV header, returns 16-bit mono samples. `reference.wav`'s header was verified
     * (via Python's `wave` module chunk offsets) to be the standard 44-byte RIFF/fmt/data layout
     * with no extra chunks before `data` -- fmt chunk is 16 bytes (ends at byte 36), data chunk
     * header is 8 bytes (ends at byte 44), and the data chunk size exactly accounts for the rest
     * of the file. If a different fixture recording is ever substituted here, this offset must be
     * re-verified rather than assumed.
     */
    private fun extractPcm16Mono(wavBytes: ByteArray): ShortArray {
        val dataStart = 44
        val shorts = ShortArray((wavBytes.size - dataStart) / 2)
        for (i in shorts.indices) {
            val lo = wavBytes[dataStart + i * 2].toInt() and 0xFF
            val hi = wavBytes[dataStart + i * 2 + 1].toInt()
            shorts[i] = ((hi shl 8) or lo).toShort()
        }
        return shorts
    }
}
